### PR TITLE
add redis-stack to docker-compose

### LINKED ISSUE #11: Amend the `docker-compose.yml` file for this course to use the Redis Stack container and re-test
This course currently uses an older version of the RediSearch container in its `docker-compose.yml` file.

Amend the `docker-compose.yml` file for this course to use the Redis Stack container and test that data loading process, the index generation commands and sample query in `README.md` all still work.

Don't rename the container - leave it named `redis-search`.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

### PR DESCRIPTION
**Pull request by AsyncDeveloper245**
Closes #11 

My discord username is  devineer#5188

Thank you!

### CODE REVIEW

**Comment by SuzeShardlow** [comment]
Thanks for the PR, @AsyncDeveloper245!  We will take a look :)

**Review by simonprickett — APPROVED** [review]
Tested locally looks good to me!

**Comment by AsyncDeveloper245** [comment]
Thank you @simonprickett

**Review by SuzeShardlow — COMMENTED** [review]
Approved!

**Comment by SuzeShardlow** [comment]
> Closes #11
> 
> My discord username is devineer#5188
> 
> Thank you!

Thanks @AsyncDeveloper245, I've given you the `Hacktoberfest 2022` role in our Discord server :)

**Pull request merged**
